In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('pokemon.csv')

In [3]:
df.info

<bound method DataFrame.info of        #                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49
1      2                Ivysaur    Grass  Poison    405  60      62       63
2      3               Venusaur    Grass  Poison    525  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123
4      4             Charmander     Fire     NaN    309  39      52       43
..   ...                    ...      ...     ...    ...  ..     ...      ...
795  719                Diancie     Rock   Fairy    600  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60
799  721              Volcanion     Fire   Water    600  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 13 columns]>

In [4]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [5]:
# No of Pokemon with attack more than 150
df.loc[df['Attack'] > 150,'Attack'].count()

np.int64(18)

In [6]:
# all the pokemons with speed less or equal to 10
slow_pokemon_df = df.loc[df['Speed'] <= 10]
slow_pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
359,328,Trapinch,Ground,NaN,290,45,100,45,45,45,10,3,False
486,438,Bonsly,Rock,NaN,290,50,80,95,10,45,10,4,False
495,446,Munchlax,Normal,NaN,390,135,85,40,40,85,5,4,False
658,597,Ferroseed,Grass,Steel,305,44,50,91,24,86,10,5,False

In [7]:
# getting the values with less than 25 sp def values
df[df['Sp. Def'] <= 25]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False
44,39,Jigglypuff,Normal,Fairy,270,115,45,20,45,25,20,1,False
97,90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,295,30,40,70,70,25,60,1,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
188,174,Igglybuff,Normal,Fairy,210,90,30,15,40,20,15,2,False
209,194,Wooper,Water,Ground,210,55,45,45,25,25,15,2,False
289,266,Silcoon,Bug,NaN,205,50,35,55,25,25,15,3,False
291,268,Cascoon,Bug,NaN,205,50,35,55,25,25,15,3,False
317,293,Whismur,Normal,NaN,240,64,51,23,51,23,28,3,False
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True
583,524,Roggenrola,Rock,NaN,280,55,75,85,25,25,15,5,False
732,664,Scatterbug,Bug,NaN,200,38,35,40,27,25,35,6,False

In [8]:
(df['Sp. Def'] <= 25).sum()

np.int64(18)

In [9]:
df['Legendary'].sum()

np.int64(65)

In [10]:
df.loc[df['Legendary']]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
156,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [11]:
# Find the pokemon which has very high defense but very low attack
df.sort_values(by=['Defense','Attack'],ascending=[False,True]).head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
223,208,Steelix,Steel,Ground,510,75,85,200,55,65,30,2,False
414,377,Regirock,Rock,NaN,580,80,100,200,50,100,50,3,True

In [12]:
# pokemon with fire and flying type
df.loc[((df['Type 1'] == 'Fire') & (df['Type 2'] == 'Flying')) | ((df['Type 1'] == 'Flying') & (df['Type 2'] == 'Fire'))]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
730,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False

In [13]:
# pokemon with fire and flying type
df.loc[(df['Type 1'] == 'Fire') & (df['Type 2'] == 'Flying'),'Name'].count()

np.int64(6)

In [14]:
# find how many poison pokemons are there in both type 1 and type 2
df.loc[((df['Type 1'] == 'Poison') | (df['Type 2'] == 'Poison'))].shape

(62, 13)

In [15]:
((df['Type 1'] == 'Poison') | (df['Type 2'] == 'Poison')).sum()

np.int64(62)

What type 1 of Ice pokemon have the strongest defense

In [16]:
df.loc[df['Type 1'] == 'Ice','Defense'].max()

184

In [17]:
df.loc[(df['Type 1'] == 'Ice') & 
       (df['Defense'] == df.loc[df['Type 1'] == 'Ice','Defense'].max())]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
789,713,Avalugg,Ice,NaN,514,95,117,184,44,46,28,6,False

In [18]:
df.loc[df['Type 1'] == 'Ice'].sort_values(by='Defense',ascending=False).head(1)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
789,713,Avalugg,Ice,NaN,514,95,117,184,44,46,28,6,False

Most common type 1 legendary pokemon

In [19]:
df.loc[df['Legendary'],'Type 1'].value_counts().head(1)

Type 1
Psychic    14
Name: count, dtype: int64

In [20]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

Most powerful pokemon from first 3 generation of type water

In [21]:
df.loc[((df['Type 1'] == 'Water') | (df['Type 2'] == 'Water')) & (df['Generation'] <= 3)].sort_values(by='Total',ascending=False).head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
422,382,KyogrePrimal Kyogre,Water,NaN,770,100,150,90,180,160,90,3,True
421,382,Kyogre,Water,NaN,670,100,100,90,150,140,90,3,True
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
283,260,SwampertMega Swampert,Water,Ground,635,100,150,110,95,110,70,3,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False

Most Powerful Dragon of last two generation

In [22]:
df.loc[((df['Type 1'] == 'Dragon') | (df['Type 2'] == 'Dragon')) & (df['Generation'].isin ([5,6]))].sort_values(by='Total',ascending=False).head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
711,646,KyuremBlack Kyurem,Dragon,Ice,700,125,170,100,120,90,95,5,True
712,646,KyuremWhite Kyurem,Dragon,Ice,700,125,120,90,170,100,95,5,True
706,643,Reshiram,Dragon,Fire,680,100,120,100,150,120,90,5,True
707,644,Zekrom,Dragon,Electric,680,100,150,120,120,100,90,5,True
710,646,Kyurem,Dragon,Ice,660,125,130,90,130,90,95,5,True

Select Most Powerful fire type pokemons

In [27]:
powerful_fire = df.loc[(df['Type 1'] == 'Fire') | (df['Type 2'] == 'Fire')].sort_values(by='Total',ascending=False)
powerful_fire.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
706,643,Reshiram,Dragon,Fire,680,100,120,100,150,120,90,5,True
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False

In [26]:
water_flying_df = df.loc[((df['Type 1'] == 'Water') & (df['Type 2'] == 'Flying')) | ((df['Type 2'] == 'Water') & (df['Type 1'] == 'Flying'))]
water_flying_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
140,130,Gyarados,Water,Flying,540,95,125,79,60,100,81,1,False
244,226,Mantine,Water,Flying,465,65,40,70,80,140,70,2,False
301,278,Wingull,Water,Flying,270,40,30,30,55,30,85,3,False
302,279,Pelipper,Water,Flying,430,60,50,100,85,70,65,3,False
508,458,Mantyke,Water,Flying,345,45,20,50,60,120,50,4,False
641,580,Ducklett,Water,Flying,305,62,44,50,44,50,55,5,False
642,581,Swanna,Water,Flying,473,75,87,63,87,63,98,5,False